### ISSUE TITLE
Penamaan list

### ISSUE THREAD

**Issue by azizramdan** [saturdayclass/hello-world-all-programming-language#32]
menurut saya lebih baik penamaan tidak perlu dikasih nomor "01-JAVASCRIPT" untuk meminimalisir bentrok dari PR, jadi cukup "Javascript" saja. Lalu di list readme nya diurutkan sesuai abjad

e.g.

A.
B.
C.
- C
- C#
- C++

J.
- Javascript

P.
- PHP

**Comment by raihan-muhammad** [comment]
Saran yang bagus nih, Akan segara kami perbaiki. Terimakasih banyak ya.

**Comment by rinaldipratama** [comment]
bagus sarannya.

**Comment by rinaldipratama** [comment]
udah saya coba perbaiki, ada di pull requests. semoga diterima hehe

**Comment by azizramdan** [comment]
@rinaldipratama mantap, readme nya dibikin link kayaknya lebih bagus, jadi waktu klik listnya misal PHP nanti ngelink ke folder PHP

**Comment by rinaldipratama** [comment]
thanks, iya. kalau bisa ditambahkan nanti.

**Comment by raihan-muhammad** [comment]
@rinaldipratama Sudah di merge ya. Terimakasih banyak sebelumnya hehe mantappp

**Comment by rinaldipratama** [comment]
sama2 😃

**Comment by afdulfauzan** [comment]
Done!
